name: Release

on:
  push:
    tags:
      - "v*.*.*"          # e.g., v0.1.0, v0.1.1

permissions:
  id-token: write         # for PyPI Trusted Publishing (OIDC)
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade packaging tooling
        run: python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build sdist and wheel
        run: python -m build --no-isolation

      - name: Twine check
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          skip-existing: true

      - name: Inspect wheel METADATA
        run: |
            python - << 'PY'
            import glob, zipfile, sys
            w = sorted(glob.glob("dist/*.whl"))[-1]
            print("Wheel:", w)
            with zipfile.ZipFile(w) as z:
                meta = [n for n in z.namelist() if n.endswith("METADATA")]
                if not meta:
                    print("No METADATA in wheel!", file=sys.stderr); sys.exit(1)
                data = z.read(meta[0]).decode()
                for k in ("Name:", "Version:"):
                    print(k, "FOUND" if k in data else "MISSING")
                print("\n--- first 40 lines ---")
                print("\n".join(data.splitlines()[:40]))
            PY
