name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clean build dirs
        run: rm -rf dist build *.egg-info src/*.egg-info

      - name: Upgrade packaging tooling
        run: python -m pip install --upgrade pip build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Show dist contents & key metadata
        run: |
          ls -l dist
          python - <<'PY'
          import glob, zipfile
          w = sorted(glob.glob("dist/*.whl"))[-1]
          with zipfile.ZipFile(w) as z:
              meta = [n for n in z.namelist() if n.endswith("METADATA")][0]
              data = z.read(meta).decode()
              for k in ("Metadata-Version:", "Name:", "Version:"):
                  print(next((l for l in data.splitlines() if l.startswith(k)), f"{k} NOT FOUND"))
          PY

      - name: Twine check (sanity)
        run: python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
          print-hash: true
